import oracledb
import os
from dotenv import load_dotenv

# Load .env values
load_dotenv()

# Connect to Oracle DB using values from your .env file
conn = oracledb.connect(
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    dsn=os.getenv("DB_DSN"),
    config_dir=os.getenv("DB_WALLET_LOCATION"),
    wallet_location=os.getenv("DB_WALLET_LOCATION"),
    wallet_password=os.getenv("DB_PASSWORD")
)

cursor = conn.cursor()

# Optional: create the table if not exists
cursor.execute("""
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE sec_filings (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      company_name VARCHAR2(50),
      quarter VARCHAR2(20),
      filing_url VARCHAR2(500)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
""")

# Insert data
data = [
    ("AMAZON", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872422000023/amzn-20220930.htm"),
    ("AMAZON", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000004/amzn-20221231.htm"),
    ("AMAZON", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000008/amzn-20230331.htm"),
    ("AMAZON", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000012/amzn-20230630.htm"),
    ("AMAZON", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000018/amzn-20230930.htm"),
    ("AMAZON", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000008/amzn-20231231.htm"),
    ("AMAZON", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000083/amzn-20240331.htm"),
    ("AMAZON", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000130/amzn-20240630.htm"),
    ("AMAZON", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000161/amzn-20240930.htm"),
    ("AMD", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248822000170/amd-20220924.htm"),
    ("AMD", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000047/amd-20221231.htm"),
    ("AMD", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000076/amd-20230401.htm"),
    ("AMD", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000139/amd-20230701.htm"),
    ("AMD", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000195/amd-20230930.htm"),
    ("AMD", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000012/amd-20231230.htm"),
    ("AMD", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000056/amd-20240330.htm"),
    ("AMD", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000123/amd-20240629.htm"),
    ("AMD", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000163/amd-20240928.htm"),
    ("ATT", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271722000102/t-20220930.htm"),
    ("ATT", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000011/t-20221231.htm"),
    ("ATT", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000022/t-20230331.htm"),
    ("ATT", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000047/t-20230630.htm"),
    ("ATT", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000057/t-20230930.htm"),
    ("ATT", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000009/t-20231231.htm"),
    ("ATT", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000022/t-20240331.htm"),
    ("ATT", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000053/t-20240630.htm"),
    ("ATT", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000059/t-20240930.htm"),
    ("COCA-COLA", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134422000042/ko-20220930.htm"),
    ("COCA-COLA", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000011/ko-20221231.htm"),
    ("COCA-COLA", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000024/ko-20230331.htm"),
    ("COCA-COLA", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000048/ko-20230630.htm"),
    ("COCA-COLA", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000060/ko-20230929.htm"),
    ("COCA-COLA", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000009/ko-20231231.htm"),
    ("COCA-COLA", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000017/ko-20240329.htm"),
    ("COCA-COLA", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000044/ko-20240628.htm"),
    ("COCA-COLA", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000060/ko-20240927.htm"),
    ("GOOGLE", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204422000090/goog-20220930.htm"),
    ("GOOGLE", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000016/goog-20221231.htm"),
    ("GOOGLE", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000045/goog-20230331.htm"),
    ("GOOGLE", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000070/goog-20230630.htm"),
    ("GOOGLE", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000094/goog-20230930.htm"),
    ("GOOGLE", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000022/goog-20231231.htm"),
    ("GOOGLE", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000053/goog-20240331.htm"),
    ("GOOGLE", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000079/goog-20240630.htm"),
    ("GOOGLE", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000118/goog-20240930.htm"),
    ("JPMORGAN", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000019617/000001961724000326/jpm-20240331.htm"),
    ("JPMORGAN", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000019617/000001961724000453/jpm-20240630.htm"),
    ("JPMORGAN", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000019617/000001961724000453/jpm-20240630.htm"),
    ("MASTERCARD", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139122000163/ma-20220930.htm"),
    ("MASTERCARD", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139123000020/ma-20221231.htm"),
    ("MASTERCARD", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139123000059/ma-20230331.htm"),
    ("MASTERCARD", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139123000131/ma-20230630.htm"),
    ("MASTERCARD", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139123000157/ma-20230930.htm"),
    ("MASTERCARD", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139124000022/ma-20231231.htm"),
    ("MASTERCARD", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139124000087/ma-20240331.htm"),
    ("MASTERCARD", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139124000161/ma-20240630.htm"),
    ("MASTERCARD", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001141391/000114139124000202/ma-20240930.htm"),
    ("MCDONALD'S", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390822000055/mcd-20220930.htm"),
    ("MCDONALD'S", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390823000012/mcd-20221231.htm"),
    ("MCDONALD'S", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390823000036/mcd-20230331.htm"),
    ("MCDONALD'S", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390823000076/mcd-20230630.htm"),
    ("MCDONALD'S", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390823000101/mcd-20230930.htm"),
    ("MCDONALD'S", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390824000072/mcd-20231231.htm"),
    ("MCDONALD'S", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390824000092/mcd-20240331.htm"),
    ("MCDONALD'S", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390824000123/mcd-20240630.htm"),
    ("MCDONALD'S", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000063908/000006390824000156/mcd-20240930.htm"),
    ("META", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680123000093/meta-20230630.htm"),
    ("META", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680123000103/meta-20230930.htm"),
    ("META", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680124000012/meta-20231231.htm"),
    ("META", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680124000049/meta-20240331.htm"),
    ("META", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680124000069/meta-20240630.htm"),
    ("META", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001326801/000132680124000081/meta-20240930.htm"),
    ("NETFLIX", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528022000368/nflx-20220930.htm"),
    ("NETFLIX", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528023000035/nflx-20221231.htm"),
    ("NETFLIX", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528023000120/nflx-20230331.htm"),
    ("NETFLIX", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528023000198/nflx-20230630.htm"),
    ("NETFLIX", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528023000273/nflx-20230930.htm"),
    ("NETFLIX", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528024000030/nflx-20231231.htm"),
    ("NETFLIX", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528024000128/nflx-20240331.htm"),
    ("NETFLIX", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528024000200/nflx-20240630.htm"),
    ("NETFLIX", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001065280/000106528024000287/nflx-20240930.htm"),
    ("PEPSICO", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747622000052/pep-20220903.htm"),
    ("PEPSICO", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747623000007/pep-20221231.htm"),
    ("PEPSICO", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747623000023/pep-20230325.htm"),
    ("PEPSICO", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747623000046/pep-20230617.htm"),
    ("PEPSICO", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747623000058/pep-20230909.htm"),
    ("PEPSICO", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747624000008/pep-20231230.htm"),
    ("PEPSICO", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747624000017/pep-20240323.htm"),
    ("PEPSICO", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747624000042/pep-20240615.htm"),
    ("PEPSICO", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000077476/000007747624000052/pep-20240907.htm"),
    ("S&P GLOBAL", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404022000171/spgi-20220930.htm"),
    ("S&P GLOBAL", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404023000058/spgi-20221231.htm"),
    ("S&P GLOBAL", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404023000113/spgi-20230331.htm"),
    ("S&P GLOBAL", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404023000159/spgi-20230630.htm"),
    ("S&P GLOBAL", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404023000193/spgi-20230930.htm"),
    ("S&P GLOBAL", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404024000071/spgi-20231231.htm"),
    ("S&P GLOBAL", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404024000125/spgi-20240331.htm"),
    ("S&P GLOBAL", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404024000150/spgi-20240630.htm"),
    ("S&P GLOBAL", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000064040/000006404024000178/spgi-20240930.htm"),
    ("VERIZON", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271222000050/vz-20220930.htm"),
    ("VERIZON", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271223000012/vz-20221231.htm"),
    ("VERIZON", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271223000029/vz-20230331.htm"),
    ("VERIZON", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271223000055/vz-20230630.htm"),
    ("VERIZON", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271223000063/vz-20230930.htm"),
    ("VERIZON", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271224000010/vz-20231231.htm"),
    ("VERIZON", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271224000029/vz-20240331.htm"),
    ("VERIZON", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271224000052/vz-20240630.htm"),
    ("VERIZON", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732712/000073271224000069/vz-20240930.htm"),
    ("TESLA", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000095017022019867/tsla-20220930.htm"),
    ("TESLA", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000095017023001409/tsla-20221231.htm"),
    ("TESLA", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000095017023013890/tsla-20230331.htm"),
    ("TESLA", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000095017023033872/tsla-20230630.htm"),
    ("TESLA", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828023034847/tsla-20230930.htm"),
    ("TESLA", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828024002390/tsla-20231231.htm"),
    ("TESLA", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828024017503/tsla-20240331.htm"),
    ("TESLA", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828024032662/tsla-20240630.htm"),
    ("TESLA", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828024043486/tsla-20240930.htm")    
]

for company, quarter, url in data:
    cursor.execute("""
        INSERT INTO sec_filings (company_name, quarter, filing_url)
        VALUES (:1, :2, :3)
    """, (company, quarter, url))

conn.commit()
cursor.close()
conn.close()

print("✅ SEC filing URLs inserted into Oracle!")
