
-- DDL for INCOME_QUARTERLY

  CREATE TABLE "ADMIN"."INCOME_QUARTERLY" 
   (	"Fiscal Quarter" VARCHAR2(255), 
	"Revenue" FLOAT(126), 
	"Revenue Growth _YoY_" FLOAT(126), 
	"Cost of Revenue" FLOAT(126), 
	"Gross Profit" FLOAT(126), 
	"Selling General and Admin" FLOAT(126), 
	"Research and Development" FLOAT(126), 
	"Operating Expenses" FLOAT(126), 
	"Operating Income" FLOAT(126), 
	"Interest Expense" FLOAT(126), 
	"Interest and Investment Income" FLOAT(126), 
	"Currency Exchange Gain _Loss_" FLOAT(126), 
	"Other Non Operating Income _Expenses_" FLOAT(126), 
	"EBT Excluding Unusual Items" FLOAT(126), 
	"Gain _Loss_ on Sale of Investments" FLOAT(126), 
	"Pretax Income" FLOAT(126), 
	"Income Tax Expense" FLOAT(126), 
	"Net Income" FLOAT(126), 
	"Net Income to Common" FLOAT(126), 
	"Net Income Growth" FLOAT(126), 
	"Shares Outstanding _Basic_" FLOAT(126), 
	"Shares Outstanding _Diluted_" FLOAT(126), 
	"Shares Change _YoY_" FLOAT(126), 
	"EPS _Basic_" FLOAT(126), 
	"EPS _Diluted_" FLOAT(126), 
	"EPS Growth" FLOAT(126), 
	"Free Cash Flow" FLOAT(126), 
	"Free Cash Flow Per Share" FLOAT(126), 
	"Dividend Per Share" FLOAT(126), 
	"Dividend Growth" FLOAT(126), 
	"Gross Margin" FLOAT(126), 
	"Operating Margin" FLOAT(126), 
	"Profit Margin" FLOAT(126), 
	"Free Cash Flow Margin" FLOAT(126), 
	"EBITDA" FLOAT(126), 
	"EBITDA Margin" FLOAT(126), 
	"D and A For EBITDA" FLOAT(126), 
	"EBIT" FLOAT(126), 
	"EBIT Margin" FLOAT(126), 
	"Effective Tax Rate" FLOAT(126), 
	"Revenue as Reported" FLOAT(126)
   )  

-- DDL for BALANCE_SHEET_QUARTERLY

  CREATE TABLE "ADMIN"."BALANCE_SHEET_QUARTERLY" 
   (	"Fiscal Quarter" VARCHAR2(255), 
	"Cash and Equivalents" FLOAT(126), 
	"Short Term Investments" FLOAT(126), 
	"Cash and Short Term Investments" FLOAT(126), 
	"Cash Growth" FLOAT(126), 
	"Accounts Receivable" FLOAT(126), 
	"Other Receivables" FLOAT(126), 
	"Receivables" FLOAT(126), 
	"Inventory" FLOAT(126), 
	"Restricted Cash" FLOAT(126), 
	"Other Current Assets" FLOAT(126), 
	"Total Current Assets" FLOAT(126), 
	"Property Plant and Equipment" FLOAT(126), 
	"Long Term Investments" FLOAT(126), 
	"Long Term Deferred Tax Assets" FLOAT(126), 
	"Other Long Term Assets" FLOAT(126), 
	"Total Assets" FLOAT(126), 
	"Accounts Payable" FLOAT(126), 
	"Short Term Debt" FLOAT(126), 
	"Current Portion of Long Term Debt" FLOAT(126), 
	"Current Portion of Leases" FLOAT(126), 
	"Current Income Taxes Payable" FLOAT(126), 
	"Current Unearned Revenue" FLOAT(126), 
	"Other Current Liabilities" FLOAT(126), 
	"Total Current Liabilities" FLOAT(126), 
	"Long Term Debt" FLOAT(126), 
	"Long Term Leases" FLOAT(126), 
	"Other Long Term Liabilities" FLOAT(126), 
	"Total Liabilities" FLOAT(126), 
	"Common Stock" FLOAT(126), 
	"Retained Earnings" FLOAT(126), 
	"Comprehensive Income and Other" FLOAT(126), 
	"Shareholders' Equity" FLOAT(126), 
	"Total Liabilities and Equity" FLOAT(126), 
	"Total Debt" FLOAT(126), 
	"Net Cash _Debt_" FLOAT(126), 
	"Net Cash Growth" FLOAT(126), 
	"Net Cash Per Share" FLOAT(126), 
	"Filing Date Shares Outstanding" FLOAT(126), 
	"Total Common Shares Outstanding" FLOAT(126), 
	"Working Capital" FLOAT(126), 
	"Book Value Per Share" FLOAT(126), 
	"Tangible Book Value" FLOAT(126), 
	"Tangible Book Value Per Share" FLOAT(126), 
	"Land" FLOAT(126), 
	"Machinery" FLOAT(126), 
	"Leasehold Improvements" FLOAT(126)
   ) 

-- DDL for CASH_FLOW_QUARTERLY

  CREATE TABLE "ADMIN"."CASH_FLOW_QUARTERLY" 
   (	"Fiscal Quarter" VARCHAR2(255), 
	"Net Income" FLOAT(126), 
	"Depreciation and Amortization" FLOAT(126), 
	"Stock Based Compensation" FLOAT(126), 
	"Other Operating Activities" FLOAT(126), 
	"Change in Accounts Receivable" FLOAT(126), 
	"Change in Inventory" FLOAT(126), 
	"Change in Accounts Payable" FLOAT(126), 
	"Change in Unearned Revenue" FLOAT(126), 
	"Change in Other Net Operating Assets" FLOAT(126), 
	"Operating Cash Flow" FLOAT(126), 
	"Operating Cash Flow Growth" FLOAT(126), 
	"Capital Expenditures" FLOAT(126), 
	"Cash Acquisitions" FLOAT(126), 
	"Investment in Securities" FLOAT(126), 
	"Other Investing Activities" FLOAT(126), 
	"Investing Cash Flow" FLOAT(126), 
	"Short Term Debt Issued" FLOAT(126), 
	"Long Term Debt Issued" FLOAT(126), 
	"Total Debt Issued" FLOAT(126), 
	"Short Term Debt Repaid" FLOAT(126), 
	"Long Term Debt Repaid" FLOAT(126), 
	"Total Debt Repaid" FLOAT(126), 
	"Net Debt Issued _Repaid_" FLOAT(126), 
	"Issuance of Common Stock" FLOAT(126), 
	"Repurchase of Common Stock" FLOAT(126), 
	"Common Dividends Paid" FLOAT(126), 
	"Other Financing Activities" FLOAT(126), 
	"Financing Cash Flow" FLOAT(126), 
	"Net Cash Flow" FLOAT(126), 
	"Free Cash Flow" FLOAT(126), 
	"Free Cash Flow Growth" FLOAT(126), 
	"Free Cash Flow Margin" FLOAT(126), 
	"Free Cash Flow Per Share" FLOAT(126), 
	"Cash Interest Paid" FLOAT(126), 
	"Cash Income Tax Paid" FLOAT(126), 
	"Levered Free Cash Flow" FLOAT(126), 
	"Unlevered Free Cash Flow" FLOAT(126), 
	"Change in Net Working Capital" FLOAT(126)
   ) 

-- DDL for RATIO_QUARTERLY

  CREATE TABLE "ADMIN"."RATIO_QUARTERLY" 
   (	"Fiscal Quarter" VARCHAR2(255), 
	"Market Capitalization" FLOAT(126), 
	"Market Cap Growth" FLOAT(126), 
	"Enterprise Value" FLOAT(126), 
	"Last Close Price" FLOAT(126), 
	"PE Ratio" FLOAT(126), 
	"Forward PE" FLOAT(126), 
	"PS Ratio" FLOAT(126), 
	"PB Ratio" FLOAT(126), 
	"P/TBV Ratio" FLOAT(126), 
	"P/FCF Ratio" FLOAT(126), 
	"P/OCF Ratio" FLOAT(126), 
	"PEG Ratio" FLOAT(126), 
	"EV/Sales Ratio" FLOAT(126), 
	"EV/EBITDA Ratio" FLOAT(126), 
	"EV/EBIT Ratio" FLOAT(126), 
	"EV/FCF Ratio" FLOAT(126), 
	"Debt / Equity Ratio" FLOAT(126), 
	"Debt / EBITDA Ratio" FLOAT(126), 
	"Debt / FCF Ratio" FLOAT(126), 
	"Asset Turnover" FLOAT(126), 
	"Inventory Turnover" FLOAT(126), 
	"Quick Ratio" FLOAT(126), 
	"Current Ratio" FLOAT(126), 
	"Return on Equity _ROE_" FLOAT(126), 
	"Return on Assets _ROA_" FLOAT(126), 
	"Return on Capital _ROIC_" FLOAT(126), 
	"Earnings Yield" FLOAT(126), 
	"FCF Yield" FLOAT(126), 
	"Dividend Yield" FLOAT(126), 
	"Payout Ratio" FLOAT(126), 
	"Buyback Yield / Dilution" FLOAT(126), 
	"Total Shareholder Return" FLOAT(126)
   )  

