[database]
user = "ADMIN"
password = "Passwordtestdb@1"
dsn = "testdb_medium"
wallet_location = "Wallet_testdb/"

[llm]
api_key = "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"
model = "llama-3.1-8b-instant"