import oracledb
import os
from dotenv import load_dotenv

# Load .env values
load_dotenv()

# Connect to Oracle DB using values from your .env file
conn = oracledb.connect(
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    dsn=os.getenv("DB_DSN"),
    config_dir=os.getenv("DB_WALLET_LOCATION"),
    wallet_location=os.getenv("DB_WALLET_LOCATION"),
    wallet_password=os.getenv("DB_PASSWORD")
)

cursor = conn.cursor()

# Optional: create the table if not exists
cursor.execute("""
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE sec_filings (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      company_name VARCHAR2(50),
      quarter VARCHAR2(20),
      filing_url VARCHAR2(500)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
""")

# Insert data
data = [
    ("AMAZON", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872422000023/amzn-20220930.htm"),
    ("AMAZON", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000004/amzn-20221231.htm"),
    ("AMAZON", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000008/amzn-20230331.htm"),
    ("AMAZON", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000012/amzn-20230630.htm"),
    ("AMAZON", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872423000018/amzn-20230930.htm"),
    ("AMAZON", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000008/amzn-20231231.htm"),
    ("AMAZON", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000083/amzn-20240331.htm"),
    ("AMAZON", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000130/amzn-20240630.htm"),
    ("AMAZON", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001018724/000101872424000161/amzn-20240930.htm"),
    ("AMD", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248822000170/amd-20220924.htm"),
    ("AMD", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000047/amd-20221231.htm"),
    ("AMD", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000076/amd-20230401.htm"),
    ("AMD", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000139/amd-20230701.htm"),
    ("AMD", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248823000195/amd-20230930.htm"),
    ("AMD", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000012/amd-20231230.htm"),
    ("AMD", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000056/amd-20240330.htm"),
    ("AMD", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000123/amd-20240629.htm"),
    ("AMD", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000002488/000000248824000163/amd-20240928.htm"),
    ("ATT", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271722000102/t-20220930.htm"),
    ("ATT", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000011/t-20221231.htm"),
    ("ATT", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000022/t-20230331.htm"),
    ("ATT", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000047/t-20230630.htm"),
    ("ATT", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271723000057/t-20230930.htm"),
    ("ATT", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000009/t-20231231.htm"),
    ("ATT", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000022/t-20240331.htm"),
    ("ATT", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000053/t-20240630.htm"),
    ("ATT", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000732717/000073271724000059/t-20240930.htm"),
    ("COCA-COLA", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134422000042/ko-20220930.htm"),
    ("COCA-COLA", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000011/ko-20221231.htm"),
    ("COCA-COLA", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000024/ko-20230331.htm"),
    ("COCA-COLA", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000048/ko-20230630.htm"),
    ("COCA-COLA", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134423000060/ko-20230929.htm"),
    ("COCA-COLA", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000009/ko-20231231.htm"),
    ("COCA-COLA", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000017/ko-20240329.htm"),
    ("COCA-COLA", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000044/ko-20240628.htm"),
    ("COCA-COLA", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0000021344/000002134424000060/ko-20240927.htm"),
    ("GOOGLE", "Q3 2022", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204422000090/goog-20220930.htm"),
    ("GOOGLE", "Q4 2022/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000016/goog-20221231.htm"),
    ("GOOGLE", "Q1 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000045/goog-20230331.htm"),
    ("GOOGLE", "Q2 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000070/goog-20230630.htm"),
    ("GOOGLE", "Q3 2023", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204423000094/goog-20230930.htm"),
    ("GOOGLE", "Q4 2023/Annual", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000022/goog-20231231.htm"),
    ("GOOGLE", "Q1 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000053/goog-20240331.htm"),
    ("GOOGLE", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000079/goog-20240630.htm"),
    ("GOOGLE", "Q3 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001652044/000165204424000118/goog-20240930.htm"),
    ("TESLA", "Q2 2024", "https://www.sec.gov/ix?doc=/Archives/edgar/data/0001318605/000162828024032662/tsla-20240630.htm")
]

for company, quarter, url in data:
    cursor.execute("""
        INSERT INTO sec_filings (company_name, quarter, filing_url)
        VALUES (:1, :2, :3)
    """, (company, quarter, url))

conn.commit()
cursor.close()
conn.close()

print("✅ SEC filing URLs inserted into Oracle!")
