name: Auto Scrape News

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FinAnswer branch
        uses: actions/checkout@v3
        with:
          ref: FinAnswer

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Scraper
        run: python backend/scraper/news_scraper.py
        env:
          POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
